server:
  port: 8044
  servlet:
    context-path: /sshop

spring:
  application:
    name: SSHOP_springboot_backend
  datasource:
    url: jdbc:postgresql://localhost:5433/sshop
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update #Hibernate ddl auto options: create, create-drop, validate, update
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
      show-sql: true

jwt:
  secretKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
